services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: icare-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
            - redis
            - mailhog
            # - reverb

    db:
        image: postgis/postgis:15-3.3-alpine
        container_name: icare-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - "${DB_PORT:-5432}:5432"
        networks:
            - app-network

    # nginx:
    #     image: nginx:latest
    #     container_name: icare-nginx
    #     restart: unless-stopped
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - .:/var/www/html
    #         - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - app
    #     networks:
    #         - app-network

    mongodb:
        image: mongo:6
        container_name: icare-mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_DATABASE: "${MONGO_DATABASE:-mydatabase}"
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
        volumes:
            - mongodata:/data/db
        ports:
            - "${MONGO_PORT:-27017}:27017"
        networks:
            - app-network

    typesense:
        image: "typesense/typesense:26.0"
        container_name: icare-typesense
        restart: unless-stopped
        ports:
            - "${TYPESENSE_PORT:-8108}:8108"
        volumes:
            - typesensedata:/data
        environment:
            TYPESENSE_API_KEY: "${TYPESENSE_API_KEY:-xyz}"
            TYPESENSE_DATA_DIR: /data
        networks:
            - app-network
        healthcheck:
            test:
                - CMD
                - wget
                - "--no-verbose"
                - "--spider"
                - "http://localhost:8108/health"
            retries: 5
            timeout: 7s

    redis:
        image: redis:alpine
        container_name: icare-redis
        restart: always
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - redisdata:/data
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog
        container_name: icare-mailhog
        restart: unless-stopped
        ports:
            - "${MAIL_PORT:-1025}:1025"
            - "${MAIL_WEB_PORT:-8025}:8025"
        networks:
            - app-network

    # reverb:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: icare-reverb
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         - ./:/var/www/html
    #     working_dir: /var/www/html
    #     networks:
    #         - app-network

networks:
    app-network:
        driver: bridge

volumes:
    pgdata:
        driver: local
    redisdata:
        driver: local
    mongodata:
        driver: local
    typesensedata:
        driver: local
